using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MauiDotNET8
{
    public static class AppConstant
    {
        public static INavigation navigation;
        public static bool IspopupClosed;
        public const string apptoken = "eyJhbGciOiJSUzI1NiIsImtpZCI6InVTLTljR0ozMzZkZjJoU3B0V2Nza2MxSEtKMktPMmprNldlMnNSdTY4UVEiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiIwMmMwYmE1ZS0wOGZiLTQ1MzktODM5OS1iYjcyNWIxOGNmZTYiLCJpc3MiOiJodHRwczovL3RyYWtrYWNsaW5pY2FsLmIyY2xvZ2luLmNvbS9lOTJiY2Q5NS03YWFhLTQwMTUtODIwZS02NTkxNTkzMGFiOWIvdjIuMC8iLCJleHAiOjE3MjEyMjg4MDEsIm5iZiI6MTcyMTIyNTIwMSwic3ViIjoiZGRlNjRhYjAtMjE5MC00MjYzLTljYTAtM2UyOTI2ZWM3MzkzIiwib2lkIjoiZGRlNjRhYjAtMjE5MC00MjYzLTljYTAtM2UyOTI2ZWM3MzkzIiwibmFtZSI6Ikd1eSBCcmFkbGV5IiwiZ2l2ZW5fbmFtZSI6Ikd1eSIsImZhbWlseV9uYW1lIjoiQnJhZGxleSIsImVtYWlsIjoidHJha2thLmNsaW5pY2FsQGdtYWlsLmNvbSIsImdyb3VwcyI6WyJQYXRpZW50cyJdLCJtYW5hZ2VyIjoiYjUxMjRhNjQtYTgwZi00NmU3LWEwYTctNGY5ZTRiYjQ5MjAzIiwiY2xpbmljIjoiODE5ZDJiZmItYzVlZi00ZDczLWJiNjMtNGY5Yjc3YWY5MjYyIiwidGlkIjoiZTkyYmNkOTUtN2FhYS00MDE1LTgyMGUtNjU5MTU5MzBhYjliIiwic2NwIjoiVGVzdFJlc3VsdHMuUmVhZFdyaXRlIiwiYXpwIjoiMzAzMjhhZmItZTc0My00YmRkLWEyNjEtZjJjMDJlZmUyZTJiIiwidmVyIjoiMS4wIiwiaWF0IjoxNzIxMjI1MjAxfQ.YtSgvRU_dzviTKLUzMe5evFe5W1A72WOYiX9FT5H2mzusqXuwvUvROeZyxPmHPMjLdt3RjYrfZScDRfmKGMBMEnkGSSdAHtYrKk6dDO3a2vi-54SkdOW9D7gP64MLKdw43F_bEr7uPNgmgw387HAukwv8CcERdivDzYIglsl-N5w5AnlNPV3dVMuGYiWk_ODn1X75tfwWtBGblNtrRq6uWIFqJTFIpLAtz7TXQUzpY9dKSx0kul-OuMzTfz35NZk8KrTVNBS-lWhoGmJi30fj4g9QtyU5koVl7i58eCJFk4ErhBO3a-YDpys1PJNwH_OqQKsCZCMvLkojuEvTAJugQ";
    }
}
