//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiDotNET8.Resources.Lanuages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiDotNET8.Resources.Lanuages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        internal static string BloodPressureButton {
            get {
                return ResourceManager.GetString("BloodPressureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Blood Pressure.
        /// </summary>
        internal static string BloodPressurePageTitle {
            get {
                return ResourceManager.GetString("BloodPressurePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood.
        /// </summary>
        internal static string BloodTabText {
            get {
                return ResourceManager.GetString("BloodTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 20 and 200.
        /// </summary>
        internal static string DiastolicValidationMessage {
            get {
                return ResourceManager.GetString("DiastolicValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ&apos;s&apos;.
        /// </summary>
        internal static string FAQTabText {
            get {
                return ResourceManager.GetString("FAQTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrakkaClinical.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTabText {
            get {
                return ResourceManager.GetString("HomeTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In partnership with:.
        /// </summary>
        internal static string InPartnershipWithText {
            get {
                return ResourceManager.GetString("InPartnershipWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string MoreTabText {
            get {
                return ResourceManager.GetString("MoreTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Blood Pressure.
        /// </summary>
        internal static string SaveBloodPressureTestButton {
            get {
                return ResourceManager.GetString("SaveBloodPressureTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutButton {
            get {
                return ResourceManager.GetString("SignOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string SummaryLabelText {
            get {
                return ResourceManager.GetString("SummaryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number between 40 and 300.
        /// </summary>
        internal static string SystolicValidationMessage {
            get {
                return ResourceManager.GetString("SystolicValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Protein.
        /// </summary>
        internal static string UrineProteinButton {
            get {
                return ResourceManager.GetString("UrineProteinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Urine Protein.
        /// </summary>
        internal static string UrineProteinPageTitle {
            get {
                return ResourceManager.GetString("UrineProteinPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine.
        /// </summary>
        internal static string UrineTabText {
            get {
                return ResourceManager.GetString("UrineTabText", resourceCulture);
            }
        }
    }
}
